# =========================
# APPLICATION
# =========================
spring.application.name=UserService
server.port=8081

# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# EUREKA CLIENT
# =========================
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# =========================
# DISTRIBUTED TRACING
# =========================
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# ZIPKIN
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# =========================
# LOGGING
# =========================
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-}] [%X{spanId:-}] [%thread] %-5level %logger - %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-}] [%X{spanId:-}] %-5level %logger - %msg%n
logging.file.name=C:/Users/Shiv/Desktop/Shiv_Java/Microservices/UserService/userservice.log
logging.level.io.micrometer.tracing=DEBUG
logging.level.brave=DEBUG
logging.level.zipkin2=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.feign=DEBUG


management.tracing.propagation.type=w3c